### ISSUE TITLE
Epic: Condor compatibility

### ISSUE THREAD

**Issue by yetson0** [block-bites/fondant-app#115]
## Condor compatibility
This is a R&D epic.

- [ ] New block structure
- [ ] New transaction structure
- [ ] Sidecar - we need to use it
- [ ] Everything that relys on js-sdk - should be easier to maintain as we can plug new sdk and just use it
- [ ] As condor is breaking update - we can offer a functionality that will help developers easily switch between casper-node versions. But this will require new architecture of the project.
- [ ] We needs to build and cache different versions of casper-node locally inside containers or provide prebuilt Docker images through the Docker hub because if user will switch between env few times a day so it needs to be fast. Maybe even it should be possible to run two networks using different node versions at the same time.
- [ ] We need to design / built more generic UI that will adapt to different data types because otherwise it will cost us too much work.

Some of the StoredValue structures are described in js-sdk.
